### ISSUE TITLE
Allow setting HTTP headers for handshake.

### ISSUE THREAD

**Issue by cmisztur** [1iveowl/WebsocketClientLite.PCL#10]
_Origin_ request header field should be settable to allow some CORS flexibility when connecting to third party servers.
https://tools.ietf.org/html/rfc6455#section-1.3

**Comment by 1iveowl** [comment]
Thanks. 

This have been implemented in v.3.6.1-beta2.

Please test and let me know.

You'll find the code in the develop branch.
