### ISSUE TITLE
Subsequent connections from same client instance fail.

### ISSUE THREAD

**Issue by cmisztur** [1iveowl/WebsocketClientLite.PCL#11]
`
client.OpenAsync()
client.CloseAsync()
client.OpenAsync()
`

Second open fails.

**Comment by 1iveowl** [comment]
Yep, I can see that. 

I've refactored to handle this. 

Please see and test v.3.6.1-beta2 and please feed your observations back to me.

You'll find the code in the develop branch.

**Comment by 1iveowl** [comment]
Should be fixed now.
