### ISSUE TITLE
Which way can I add custom headers?

### ISSUE THREAD

**Issue by Alhantro** [1iveowl/WebsocketClientLite.PCL#2]
When I'm using SetRequestHeader(header.Key, header.Value);
not implemented exception thrown.

**Comment by 1iveowl** [comment]
Hi Alhantro,

It you by "Headers" mean "Sub Protocol" then please look at the Readme Again. I just updated it to reflect this newly added feature, just as I just updated the Nuget version to 2.0.2.

Does this help?
