### ISSUE TITLE
Message Size greater than 126 Characters

### ISSUE THREAD

**Issue by alberk8** [1iveowl/WebsocketClientLite.PCL#22]
Hi 
I have a json string greater than 126 characters but shorter than 1024 character in length,  The problem is that the SendTextAsync is sending 0 bytes across to the websocket server.  if the string is less than 126 chars then the server will receive it without problems.

How do I get around this without other complication?   Thank you.

`await websocketClient.SendTextAsync(jsonData);`

**Comment by 1iveowl** [comment]
Thank you. I will look into this.

**Comment by 1iveowl** [comment]
There was a bug. It gone now. Try NuGet v. 3.6.7.

Please report back when you have tested if it works, so I can close this issue.

**Comment by alberk8** [comment]
Hi,

I looks like the problem is fixed now.  Will communicate if we encounter any more problems.  Thank you.
