### ISSUE TITLE
TLS Cipher Suite

### ISSUE THREAD

**Issue by alberk8** [1iveowl/WebsocketClientLite.PCL#30]
I have a simple test app written in Xamarin for Android and connecting to my wss via ngnix.

In Ngnix if I set the following configuration, the app will error out when I enablethe ssl_cipher otherwise it would work well with TLS.   My question is what is the strongest cipher that I can use for targeting Android 4.4 and above.  The cipher suite works with a web browser websocket connection to the wss on the same server, so I know that my wss is working and the trouble would be the cipher suite for Android.  Any pointer would be appreciated.

`ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';`

Thank you.

**Comment by 1iveowl** [comment]
Unfortunately I don't know anything about selv ciphers.

All I know is that there is a new mono release that talks about ssl. Try looking at momo-project.com.

**Comment by 1iveowl** [comment]
Came across this by coincidence [SSL TLS Support in Mono](https://github.com/duplicati/duplicati/wiki/SSL-TLS-support-in-Mono). Useful?

**Comment by 1iveowl** [comment]
This seems to have been fixed in the latest Mono release 4.8.x. [Mono 4.8.0 Release Notes](http://www.mono-project.com/docs/about-mono/releases/4.8.0/)

Can you please confirm/disconfirm? Thank you.
