### ISSUE TITLE
Unable to be portable due to System.Reactive.Windows.Threading

### ISSUE THREAD

**Issue by Workshop2** [1iveowl/WebsocketClientLite.PCL#38]
I have just analysed my Nuget package using WebsocketClientLite.PCL and it says that the above inherited package isn't portable.

Are you aware of this? 

https://icanhasdot.net/result?github=noobot~2Fslackconnector

**Comment by 1iveowl** [comment]
No, and it sounds strange as I'm pretty sure that the System.Reactive is portable. 

Anyhow, not much I can do about it as it is in a NuGet provided by Microsoft.

**Comment by Workshop2** [comment]
I assumed as much, wasn't sure if you were aware. Thanks :)
