### ISSUE TITLE
Ignore invalid ssl cert fails

### ISSUE THREAD

**Issue by ByronAP** [1iveowl/WebsocketClientLite.PCL#39]
When I set it to ignore invalid ssl certs it seems to fail to do so. On .net core

**Comment by 1iveowl** [comment]
Can you be more specific? 

I have tested this scenario and did not find any issue with it. What sort of invalid cert are we talking about?

**Comment by ByronAP** [comment]
our cert is valid for external requests to the domain name however if I use the machine name which returns the same cert but will fail checks because the domain is wrong I get a connection failure. I will do more digging and provide more indepth info as soon as I can (it's sunday and I am exhausted).
