### ISSUE TITLE
Remove default subprotocol added

### ISSUE THREAD

**Issue by Raj123456788** [1iveowl/WebsocketClientLite.PCL#4]
I updated your nugget package https://github.com/1iveowl/WebsocketClientLite.PCL/blob/e159d85b4f2c67c7fa262e635383bae8c85424a5/src/main/Helper/ClientHandShake.cs

has default subprotocols added: Chat & Super chat. just FYI

Packages folder is missing when I downloaded the project again.

**Comment by Raj123456788** [comment]
Getting this error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'HttpMachine.PCL 2.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile7', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by 1iveowl** [comment]
What Nuget version of WebsocketClientLite are you using?

Version 2.x is based on .NET Standard 1.4. If you are creating a library it must also target .NET Standard 1.4+. It you are creating a PCL based on Profile 7 then you must use WebsocketClientLite version 1.x.

**Comment by Raj123456788** [comment]
Works after updating the package. Thanks!

**Comment by Raj123456788** [comment]
Works after updating the package. Thanks!
