### ISSUE TITLE
Visual Studio 2015 Update 3 with Xamarin

### ISSUE THREAD

**Issue by alberk8** [1iveowl/WebsocketClientLite.PCL#42]
Hi,

I tried to use this library with Xamarin for Android.  The nuget just hang there when I tried to install it via nuget.  There is no further error or log that I can get beside the one below.  I can install other nuget package like newtonsoft.json so I know that the connectivity to nuget is good.  What could be wrong here? 

`
Attempting to gather dependency information for package 'WebsocketClientLite.PCL.4.1.2' with respect to project 'TestApp', targeting 'MonoAndroid,Version=v8.0'`

**Comment by alberk8** [comment]
I have to nuget package manager to 3.5 for it to work

**Comment by 1iveowl** [comment]
The latest version of NuGet is 4.3.
Have you tried: `Nuget.exe update -self`?

**Comment by 1iveowl** [comment]
Also, I'm using Visual Studio 2017, so maybe try that too.
