### ISSUE TITLE
Sec-WebSocket-Protocol is aggregated wrong

### ISSUE THREAD

**Issue by dietert** [1iveowl/WebsocketClientLite.PCL#44]
Hello,

Sec-WebSocket-Protocol is aggregated wrong

See:
https://github.com/1iveowl/WebsocketClientLite.PCL/blob/119be3d3e118751b06c22d6157526e6d93253677/src/main/WebsocketClientLite.Netstandard/Helper/ClientHandShake.cs#L43

E.g: following line
> List<string> subprotocols = new List<string> {"soap", "json"};

Will insert into the headers (wrong)
> Sec-WebSocket-Protocol: , soap, json

Instead of (correct)
> Sec-WebSocket-Protocol: soap, json

 Possible solution:
> var subprotocol = $"Sec-WebSocket-Protocol: {subprotocols.Aggregate((current, protocol) => $"{current}, {protocol}")}";

**Comment by 1iveowl** [comment]
Good catch. It's been fixed. in version 4.14.
