### ISSUE TITLE
Question : WebsocketClientLite versus the Microsoft client for performance

### ISSUE THREAD

**Issue by brooksyott** [1iveowl/WebsocketClientLite.PCL#53]
Good day,

Sorry if this is not the right forum to ask a question.
I am considering using this library for a websocket test client, similar to those that can be found as add-ins in Chrome etc. I would be wanting to create 100's of websockets at a time likely.

I'm curious if you have any idea how this library compares to the Microsoft client from a performance perspective, and if you think the threading should be ok to to start many websockets at a time.

Really appreciate the help,

Thanks you.

**Comment by 1iveowl** [comment]
I think the library should be pretty fast, but I don't know how this compares to the Microsoft client.
