### ISSUE TITLE
NuGet package versions 7.0.0 and 7.0.1 actually contain version 6.4.0

### ISSUE THREAD

**Issue by ErisApps** [1iveowl/WebsocketClientLite.PCL#67]
Hi,

I noticed that a new major build was released on NuGet a little while ago, however... I couldn't get the console test program to compile with the latest versions (7.0.0 and 7.0.1). Upon further investigation using the FuGet and NuGet package explorers, I noticed that the codebase looked pretty identical to the one of 6.4.0 which makes me want to believe that an issue happened somewhere during the upload to NuGet 😅 
So it would be much appreciated if you could double check the NuGet releases as this looks like a really promising library.

![image](https://user-images.githubusercontent.com/25928757/163728138-e39de8a4-f6d6-4618-b297-810b965c8e97.png)

Src: https://www.fuget.org/packages/WebsocketClientLite.PCL/7.0.1/lib/netstandard2.0/WebsocketClientLite.PCL.dll/WebsocketClientLite.PCL/MessageWebSocketRx

![image](https://user-images.githubusercontent.com/25928757/163728143-81181e95-06a2-4ec1-9019-a1d63bb1ff03.png)
Src: https://nuget.info/packages/WebsocketClientLite.PCL/7.0.1

**Comment by 1iveowl** [comment]
Thanks for raising this @ErisApps!

You are absolutely right. There's an issue with the NuGet. It will be fixed in a minute.

**Comment by ErisApps** [comment]
Noticed that the latest versions had their TFM changed to netstandard2.1 (compared to netstandard2.0).
This sadly prevents me from consuming the package as my own project targets netstandard2.0 due to limitations of the Unity Mono runtime. Would you be opposed if I tried to add support back for .NET Standard 2.0?
