### ISSUE TITLE
IsConnected always true.

### ISSUE THREAD

**Issue by cmisztur** [1iveowl/WebsocketClientLite.PCL#9]
IsConnected is never set to false after CloseAsync().

**Comment by 1iveowl** [comment]
Should be fixed now. Please confirm?

**Comment by cmisztur** [comment]
Probably need one more here when server requests a disconnect: https://github.com/1iveowl/WebsocketClientLite.PCL/blob/master/src/main/Service/WebsocketListener.cs#L55

**Comment by 1iveowl** [comment]
Thanks. 

Please see and test v.3.6.1-beta2 and feed your observations back to me.

You'll find the code in the develop branch.

**Comment by cmisztur** [comment]
Ok, before I continue, I want to check with you if these are the correct libraries:
http://imgur.com/a/YGvdn

Also I had to bump your libraries to .NETStandard1.5.  One complained that a dependency needed 1.3 and all were at 1.2 so I just bumped them to 1.5.

**Comment by 1iveowl** [comment]
Yes and no. I would suggest that you test by using the NuGet. 

The network stack is not fully complete in .NET Standard (will be when Microsoft release .NET Standard 2.0 some time next year I suppose). To work around this I'm using [Bait and Switch](http://log.paulbetts.org/the-bait-and-switch-pcl-trick/) to provide your library with either PCL library (for anything below .NET Standard 1.5) or else the .NET Standard 1.5 library.

**Comment by cmisztur** [comment]
Cool, neat trick!  Ok, I went back to nuget.
I'm leaving this open still since the code around cancellation token is different now.

**Comment by 1iveowl** [comment]
Closing as the cancellation token part has a seperate issue
